"""add assignments and rubric tables

Revision ID: 2014e3cbe4b5
Revises: ebf987d014a3
Create Date: 2026-04-09 13:31:24.760219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2014e3cbe4b5'
down_revision: Union[str, None] = 'ebf987d014a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('submission_type', sa.Enum('text', 'file', 'both', name='submissiontype'), nullable=False),
    sa.Column('max_drafts', sa.Integer(), nullable=False),
    sa.Column('late_policy', sa.Enum('block', 'penalty', 'allow', name='latepolicy'), nullable=False),
    sa.Column('penalty_per_day', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_classroom_id'), 'assignments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_assignments_deadline'), 'assignments', ['deadline'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('levels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubric_criteria_assignment_id'), 'rubric_criteria', ['assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rubric_criteria_assignment_id'), table_name='rubric_criteria')
    op.drop_table('rubric_criteria')
    op.drop_index(op.f('ix_assignments_deadline'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_classroom_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
