"""add ai feedback table

Revision ID: 245171d13cac
Revises: e64bf7887fe7
Create Date: 2026-04-11 01:10:05.807829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245171d13cac'
down_revision: Union[str, None] = 'e64bf7887fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.UUID(), nullable=False),
    sa.Column('estimated_score', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('suggested_level', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criteria.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_criterion_id'), 'ai_feedback', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_submission_id'), 'ai_feedback', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_feedback_submission_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_criterion_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    # ### end Alembic commands ###
