"""add submissions table

Revision ID: e64bf7887fe7
Revises: 2014e3cbe4b5
Create Date: 2026-04-11 01:02:04.767695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64bf7887fe7'
down_revision: Union[str, None] = '2014e3cbe4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('draft_number', sa.Integer(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_assignment_student_final', 'submissions', ['assignment_id', 'student_id', 'is_final'], unique=False)
    op.create_index('uq_final_submission', 'submissions', ['assignment_id', 'student_id'], unique=True, postgresql_where=sa.text('is_final = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_final_submission', table_name='submissions', postgresql_where=sa.text('is_final = true'))
    op.drop_index('ix_submissions_assignment_student_final', table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
